### ISSUE TITLE
Downloader

### ISSUE THREAD

**Issue by BrianG61UK** [ribbons/RadioDownloader#223]
Please fix RadioDownloader so it can download episode 135 from:
http://rss.acast.com/techsmessage
Thank you.

**Comment by ribbons** [comment]
Thanks for your bug report.  I've just tried downloading episode 135 of the RSS feed that you shared and it works okay for me.

To help me narrow the issue down, could you give me a couple of bits of info:
- The version of Radio Downloader that you are you using
- The error message that you are getting?  A screenshot can also be handy.

**Comment by BrianG61UK** [comment]
Thank you.

I am using Radio Downloader 0.30-0-g2b64de7

Screenshot of error is attached.

Brian Gregory.
bdgregory@gmail.com
www.Brian-Gregory.me.uk
(Home)

**Comment by ribbons** [comment]
> Screenshot of error is attached.

Unfortunately the screenshot didn't come through, could you try directly uploading it to the issue on GitHub instead of emailing it?  You can drag and drop the image file into the comment box.

**Comment by BrianG61UK** [comment]
Sorry. Here it is:
![rdl err 1](https://user-images.githubusercontent.com/6334848/39445304-8a88171a-4cb2-11e8-9109-2eb80e04f652.png)

**Comment by ribbons** [comment]
No worries :smiley: 

If you click on the failed download what error message does it show in the sidebar?

**Comment by ribbons** [comment]
Okay.  Could you install the build from https://ci.appveyor.com/project/ribbons/radiodownloader/build/165/job/rlrttjyyp9yoancd/artifacts and retry the download?

**Comment by BrianG61UK** [comment]
I installed the new version.
Radio Downloader 0.30-74-89488aa9
The error looks the same but when I press report error I am now given a report number.
I reported the error as, if I remember correctly, 55791, 55792 and 55793.

**Comment by ribbons** [comment]
Perfect, thanks - this is the exception:

```
System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at PodcastProvider.PodcastProvider.DownloadProgramme(String progExtId, String episodeExtId, ProgrammeInfo progInfo, EpisodeInfo epInfo, String finalName) in C:\projects\radiodownloader\Providers\PodcastProvider\Classes\PodcastProvider.cs:line 455
   at RadioDld.DownloadHandler.DownloadProgThread() in C:\projects\radiodownloader\Classes\DownloadHandler.cs:line 224
```

I can also reproduce the issue under Windows 7.  Think it might be TLS related in some way, but I'm not totally sure...

**Comment by BrianG61UK** [comment]
Thanks for the update.

**Comment by ribbons** [comment]
Could you try the build from here and let me know if it makes a difference:
https://ci.appveyor.com/project/ribbons/radiodownloader/build/175/job/ta4sakcq54c2gfpy/artifacts

**Comment by BrianG61UK** [comment]
Thank you very much, that seems to have fixed it.
